language: node_js
node_js:
  - "10.13.0"
script:
  - npm install
  - npm install coveralls
  - npm run test:ci
  - bash ./start_local_instance.sh
  - npm run test:integration

after_success:
  - coveralls < coverage/lcov.info
